### ISSUE TITLE
MongoError: Authentication failed.

### ISSUE THREAD

**Issue by joshuadiezmo** [parse-community/parse-server-example#120]
Getting this error in latest update but when try it on old version its working just fine.
node_modules/mongodb-core/lib/connection/connection.js:285:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:523:20)
Uncaught internal server error. { [MongoError: Authentication failed.]
  name: 'MongoError',
  message: 'Authentication failed.',
  ok: 0,
  code: 18,
  errmsg: 'Authentication failed.' } MongoError: Authentication failed.

**Comment by msniff16** [comment]
confirmed. me too.

**Comment by MylesHarding** [comment]
same issue for me also.

**Comment by prakash-subramani** [comment]
yeah i am also facing this
