### ISSUE TITLE
What all features are not available in parse-server-example ? password resetting via mail is not available ??

### ISSUE THREAD

**Issue by syampsijk** [parse-community/parse-server-example#137]
What all features are not available in parse-server-example ? 
password resetting via mail is not available ??
Could anyone provide what all features are not available

**Comment by noder199** [comment]
The documentation on this [page ](https://github.com/ParsePlatform/parse-server)will answer your questions.

Password resetting via email is available, just follow the instructions further down the linked page.
Right now there are a number of features not available, for instance cloud jobs must be done manually. Analytics are also no longer around. For the most part, all features from parse exist and there are even some new ones like [livequery](https://github.com/ParsePlatform/parse-server/wiki/Parse-LiveQuery).
