### ISSUE TITLE
Any way to keep package.json in sync with parse server version?

### ISSUE THREAD

**Issue by gateway** [parse-community/parse-server-example#168]
I know we can do PR's but each time I dont want to have to always do that.. any thoughts on auto updating the package.json from the parse server version #? 

I know its crazy talk but just thought I would ask :)

**Comment by drew-gross** [comment]
Not sure what you are asking for here. Both Parse Server and Parse Dashboard detect their own version by reading their `package.json` file. Parse Dashboard also loads the most recent `package.json` from `npm` in order to display new features that are only available in newer versions.

**Comment by gateway** [comment]
Each time someone clones the parse server example, its package.json https://github.com/ParsePlatform/parse-server-example/blob/master/package.json has an older version of the server, I usually have to edit it since we are up to 2.2.7 now on the parse-server git depo.  Wasnt sure if we can keep the parse-example-server package.json code block in sync with the latest release of parse-server..

Current package.json for parse-server-example

```
  "license": "MIT",
  "dependencies": {
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.8.0",
    "parse-server": "~2.2.2"
  },

```

which then If im not being a retard I have to switch to 

```
  "license": "MIT",
  "dependencies": {
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.8.0",
    "parse-server": "~2.2.7"
  },
```

just rambling a thought out.

**Comment by drew-gross** [comment]
We can use `*` as the version.

**Comment by gateway** [comment]
that would be an idea

**Comment by Theizu** [comment]
how do i update my parse-server-example from heroku?
