### ISSUE TITLE
"No reachable servers" when migration to self hosted server

### ISSUE THREAD

**Issue by w3care25** [parse-community/parse-server-example#176]
I am trying to migrate my app from parse to self hosted server.

But unable to migrate database when inserting mongodb database URI and start migration it shows :"No Reachable Server"

I am using mongoDb URI as follows: mongodb://user:password@IP-address:27017/parse

Any idea how to fix this ?

**Comment by drew-gross** [comment]
Your mongoDB is not accessible from our servers. Can you connect using the mongo CLI?
