### ISSUE TITLE
EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by mr-rick** [parse-community/parse-server-example#186]
When I do a docker build, I'm getting:

npm ERR! EXDEV: cross-device link not permitted, rename '/parse/node_modules/escodegen/node_modules/esprima' -> '/parse/node_modules/degenerator/node_modules/escodegen/node_modules/esprima'

ubuntu-16.04
docker-engine-1.11.1-0~xenial

**Comment by gowridev** [comment]
I too got similar error
npm ERR! Linux 4.4.8-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path /parse/node_modules/ast-types
npm ERR! code EXDEV
npm ERR! errno -18
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename '/parse/node_modules/ast-types' -> '/parse/node_modules/.ast-types.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /parse/npm-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 238

**Comment by gowridev** [comment]
I am able to resolve this issue. 
Upgrade to new NPM and node js

 Commands to update npm
           $ sudo npm cache clean -f
           $ sudo npm install -g n
 Commands to udpate node in mac
            $ node -v
            $ brew upgrade node
            $node -v


npm ERR! EXDEV: cross-device link not permitted, rename '/parse/node_modules/ast-types' -> '/parse/node_modules/.ast-types.DELETE'
Remove or move node_modules folder and re-run the docker command.
