### ISSUE TITLE
Multiple Problems - Hosted on Azure

### ISSUE THREAD

**Issue by p-rryr-se** [parse-community/parse-server-example#189]
Hey there, I've been having a few problems for a while now and I still haven't figured them all out. I'm not too sure if they're all related either.

First, when I try to call a PFCloud function in Objective-C I always get this error returned

> NSDebugDescription = "JSON text did not start with array or object and option to allow fragments not set.";

It doesn't matter what Cloud code function it is either, even the 'hello' function returns this.

Secondly, when I try to access **mysite.azurewebsites.net** I get the error

> Cannot GET /

Thirdly, trying to access **mysite.azurewebsites.net/parse**

> {"error":"unauthorized"}

And finally, trying to access the server via the Parse Dashboard (**mysite.azurewebsites.net/parse-dashboard**) it says

> Server not reachable: unable to connect to server

Apart from all this, my parse server works fine and does everything I want it to do. I'm mainly concerned about the cloud code as I need to access it. Again I'm not sure if all of this is related, or if it has something to do with Azure.

Any help would be greatly appreciated

**Comment by chrisfaig** [comment]
Facing the same problem. 
I had a instance working, but from time to time I had to reset the web services due hang..... 
So I deleted the instance and redeploy... never got a new installation to work correctly.
always facing the "Cannot GET /" and sometimes issue to install the dashborard (time out issue).

**Comment by p-rryr-se** [comment]
Glad to know I'm not the only one with these problems. Hopefully there's a fix!

**Comment by digivish** [comment]
I have the same exact issue.

**Comment by bigdoghung** [comment]
Azure now has a new template stack that you can use. It was really simple and only took about 5 minutes. Make sure you choose Parse Managed
