### ISSUE TITLE
Enable Push Notifications after Elastic Beanstalk deployment

### ISSUE THREAD

**Issue by gkswamy98** [parse-community/parse-server-example#196]
I've been able to successfully deploy Parse Server to AWS Elastic Beanstalk using the button on [https://github.com/ParsePlatform/parse-server-example](https://github.com/ParsePlatform/parse-server-example), update my iOS client with the appropriate custom ParseClientConfiguration, and create a _PushStatus document on my mLab managed mongoDB through a curl request. However, when I do the latter, my sample iOS device does not receive a APNS Push Notification. How do I add a .p12 certificate and specify my bundle id and development status on EB?

**Comment by allanascano-otus** [comment]
please follow this to setup your Parse Server on AWS
[](https://github.com/ParsePlatform/parse-server/wiki/Push)

and this to setup your ios app to receive push
[](https://github.com/ParsePlatform/Parse-Server/wiki/Push-Configuring-Clients)

**Comment by david-koch-pro** [comment]
I deployed parse server to AWS Elastic Beanstalk successfully but couldn't get push notification.
"Error:XMLHttpRequest failed: 'Unable to connect to the Parse API'"
How to connect Parse API? I think server configuration has no problem.

**Comment by gkswamy98** [comment]
Update: Downloaded code through EB CLI and edited index.js and uploaded .p12 certificate. However, now the pushes say "sending" on dashboard and have status of "pending" on mLab database for hours on end. How do I get the pushes to actually get sent?

**Comment by lifeisfunny** [comment]
I would do a local machine test first.

**Comment by david-koch-pro** [comment]
I don't get any error but my device couldn't get push notification.

**Comment by vineetbindal** [comment]
@david-koch-pro , @gkswamy98    Were you guys able to resolve it? Can you guys add instructions here ?

**Comment by david-koch-pro** [comment]
Originally, I've uploaded .p12 production file and couldn't receive notification on my device. So I recreated certificated file for both of development and distribution and uploaded again.
Now, I can receive any push message on device.

**Comment by david-koch-pro** [comment]
push: {
    ios: [
      {
        pfx: 'Certificates.p12',
        bundleId: 'com.asdf.qwer',
        production: true
      },
      {
        pfx: 'CertificatesDev.p12',
        bundleId: 'com.asdf.qwer',
        production: false
      }
    ]
  }

**Comment by vineetbindal** [comment]
@david-koch-pro Thanks. I regenerated the certs.Still not getting the notifications. 

Here is my push code:
    var query = new Parse.Query(Parse.Installation);
    query.equalTo("installationId", instalationId);
    Push.send({
            where: query,
            data: {
                header: "Status : " + status ,
                alertMessage: receiverNumber + " " + status,
                alert: receiverNumber + " " + status,
                badge: "Increment",
                sound: "cat.caf",
                receiverName : receiverName,
                receiverNumber : receiverNumber,
                message : message,
                status : status
            }
        },{
            success: function() {
                console.log("notification sent to [" + receiverName + ";" + receiverNumber + "; Message : " + message +"]");
            },
            error: function(error) {
                console.log("Error sending senderPush: " + error.message);
            },
            useMasterKey: true
        });

I can see success statements printing on console but no push being received.

**Comment by lifeisfunny** [comment]
I had same problem when I test on my local machine Mac OS X.     But once it's on the aws ebs.  , everything is fine.   So I would suggest when you test your push notification.  , setup one a nodejs server machine.  And try again.

**Comment by lifeisfunny** [comment]
In my case. It's was apeared to be a thread issue.
