### ISSUE TITLE
Can't git clone parse-server-example

### ISSUE THREAD

**Issue by nimach** [parse-community/parse-server-example#197]
Hi,
I use below command to add parse-server-example on centos 6.x:
`git clone git://github.com/ParsePlatform/parse-server-example.git`

but I get this error:
`fatal: unable to connect to github.com:`
`github.com[0: 192.30.252.130]: errno=Connection timed out`

How can I fix it?
Thanks.

**Comment by karajrish** [comment]
Are you running on a proxy server. If yes configure it for git:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

change proxyuser to your proxy user
change proxypwd to your proxy password
change proxy.server.com to the URL of your proxy server
change 8080 to the proxy port configured on your proxy server
If you decide at any time to reset this proxy and work without proxy:

Command to use:

`git config --global --unset http.proxy`

Finally, to check the currently set proxy:

`git config --global --get http.proxy`
