### ISSUE TITLE
npm start is not working 

### ISSUE THREAD

**Issue by matt212** [parse-community/parse-server-example#204]
Hi, 

I have installed all dependencies and when i execute npm start i get below error , 

>   if (!_path2.default.isAbsolute(logsFolder)) {
>                       ^
> TypeError: Object #<Object> has no method 'isAbsolute'
>     at configureLogger (/home/ubuntu/parse-server/node_modules/parse-server/lib/                                                                                        logger.js:67:23)

Please note I already create symbolic link to node folder
Please find attached screenshot for you reference
![parse-server](https://cloud.githubusercontent.com/assets/1698139/15563437/5720bef2-22bd-11e6-9987-fd6e82b8d42e.png)

**Comment by raj-maurya** [comment]
@matt212 

I am getting the same error.  I am using ubuntu and have installed all the dependencies.

**Comment by raj-maurya** [comment]
Greetings: @matt212 

I have fixed my error by following http://tecadmin.net/upgrade-nodejs-via-npm/
this means you need to Upgrade Node.js via NPM, give it a try.
