### ISSUE TITLE
failed to load resource: 403

### ISSUE THREAD

**Issue by PeterKaminski09** [parse-community/parse-server-example#207]
![screen shot 2016-05-26 at 2 04 23 pm](https://cloud.githubusercontent.com/assets/5935411/15584928/ce682d6e-234a-11e6-9f3b-aa066841c9e7.JPEG)
I'm getting this error when I try and run the code. It was working for me earlier this week--not sure why it doesn't work now. 

Here is all that I have changed in the file: 
var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/dev',
  cloud:  __dirname + '/cloud/main.js',
  appId:  'XXX',
  masterKey: 'XXX', //Add your master key here. Keep it secret!
  serverURL: 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});

**Comment by PeterKaminski09** [comment]
Note: this is when using the /test post function

**Comment by ludapops** [comment]
Also experiencing this issue, I cloned the example server then inputed my keys, next I initialized parse in my angular app butI am getting "403 forbidden error" for my rest api calls. Any suggestions?

**Comment by leabdalla** [comment]
same problem here on /test example

**Comment by c-warnick** [comment]
Check /public/js/script.js and find the XHR.POST and XHR.GET functions near the bottom.  You see

`this.xhttp.setRequestHeader("X-Parse-Application-Id", "myAppId");`

Make sure you've replaced "myAppId" with your appId 

This was the issue I was running into.  Works fine now.

**Comment by mo-mozafarian** [comment]
@c-warnick Thanks! Fixed mine.
