### ISSUE TITLE
added a file through local parse dashboard but not able to fetch file from Parse Dashboard

### ISSUE THREAD

**Issue by aggarwal23deepak** [parse-community/parse-server-example#211]
uploaded a file from "http://52.39.100.79:4040/apps/" (local parse dashboard) and url path created = "http://52.39.100.79:1337/parse/files/C1VnZXIeJNdNJ9O2XEUtwLTsliB5n9JJJogJaqhD/37a35b2aedaf7ef6d8a311a4d493df80_Another%20Fashionista.jpg"
but when  
fetch file from "dashboard.parse.com" 
url = "http://files.parse.com/e778c7af-d0d7-49f9-87a2-9ffa8f020891/37a35b2aedaf7ef6d8a311a4d493df80_Another%20Fashionista.jpg" 

"This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A8E05071BC963484</RequestId>
<HostId>
UaqYAae2OGOcN07RriU/MlW9otrjPDrXVs0g5lYSUBSQRdOp+9XAexQw7p891NNnXJK/zHIMkFg=
</HostId>
</Error>"

**Comment by manishnath** [comment]
Facing the same issue. Is there a solution or workaround for this?

**Comment by manishnath** [comment]
Any solutions on file migration here?

**Comment by khanamir** [comment]
I'm facing the same issue as well. Please provide any workaround.
