### ISSUE TITLE
package.json dependencies

### ISSUE THREAD

**Issue by sylvainlap** [parse-community/parse-server-example#212]
In the package.json, dependencies are : 

```
"dependencies": {
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.8.0",
    "parse-server": "~2.2.2"
  },
```

however, kerberos & parse are never used in this project, and are not part of any peerDependencies. Why would you keep them ?

**Comment by ericrini** [comment]
This is a good question because the kerberos module seems to be difficult to build.
