### ISSUE TITLE
Queries are slow?

### ISSUE THREAD

**Issue by Twizzlerfw** [parse-community/parse-server-example#214]
I am using AWS and mLab. I upgraded mLab to the first option but it did not make a difference, so that means that the open source parse server is slow. When I was on parse.com it was a lot faster so I am not sure what changed? If any one could help that would be great!

**Comment by sprabs** [comment]
We are experiencing high latency as well, especially when we are doing many reads/writes through REST API. Were you able to find a fix for this?

**Comment by jeffhuangtw** [comment]
You need to figure out what's the slowest bottleneck of each API call.
Is the bottleneck on the Parse Server or the bottleneck on the mLab Database ?
Or the bottleneck is between the connection speed from Server to the database ?

You should be able to identify the database query speed from mLab dashboard.
And maybe you can check the execution time by adding some log at Parse Server.
