### ISSUE TITLE
HTTPS deployment with AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by PeterKaminski09** [parse-community/parse-server-example#224]
Does anyone have any idea where to begin with making the parse server https secure? 

The AWS documentation has been thoroughly unhelpful.

**Comment by rrroni** [comment]
Here's a broad outline:
Requirements: 
- your own domain
- a load balancer at AWS

Process:
http://docs.aws.amazon.com/acm/latest/userguide/gs-elb.html
- Get a certificate for *.yourdomain.com via ACM, verify it
- Set up a hosted zone at Route 53 for your domain
      - A Record alias with target as the load balancer
      - SOA
      - Will give you NS records to which you point your DNS at the registrar
- Enable Beanstalk Environment to use Autoscaling and ELB
- Enable ELB manually to use AWS Certificate by adding a listener to its security group
      - HTTP 	port 80
      - HTTPS 	port 443	HTTP		port 80	SSL certificate from ACM
- Get the EC2 ID, find the corresponding EC2 security group
- On that security group, set inbound rules 
     - HTTP, TCP, port 80, load balancer
     - HTTPS	TCP	443	0.0.0.0/0

I recommend going for biz level AWS support for this process.
