### ISSUE TITLE
Update Parse server on ubuntu

### ISSUE THREAD

**Issue by sashakhail** [parse-community/parse-server-example#229]
How can I update latest version of Parse Server however I am using parse Example server on Ubuntu where is my installed server version is 2.2.12 and at this time the new release parse server version is 2.2.15, I know how to update Parse server but did not know how to update it using parse example server.
Please help

**Comment by acegreen** [comment]
@sashakhail 

-git clone https://github.com/ParsePlatform/parse-server-example.git <NEW_DIRECTORY_NAME> 
- npm install 
- copy your index.js, cloud code, push certificates etc from the old directory
- keep your original directory as backup (trust me)

**Comment by Sadmansamee** [comment]
so every time a new directory? @acegreen

**Comment by acegreen** [comment]
@Sadmansamee every time you clone a new instance yes. In terms of backup, I like to leave 2 backups, and my current version. So I'm always left with 3. For example
2.1.15, 2.1.16, 2.1.17 
When 2.1.18 comes, I would install it first as a new instance and eventually delete 2.1.15... And so on.
