### ISSUE TITLE
After migration from Parse to Heroku/mLab, Push notification are still on Parse side

### ISSUE THREAD

**Issue by ghost** [parse-community/parse-server-example#230]
Hello. I try to found resolution off this problem all over the 1st and 2nd google pages and here on github but actualy I can't even found similar issue. Point is that after migration from Parse to Heroku (Parse server) and mLab (MongoDB) using this tutorial https://learnappmaking.com/how-to-migrate-parse-app-parse-server-heroku-mongolab/, I get everything working except Push notification. When I sent push notification, even I am using curl or do it directly from Parse server, I could see that Push notification on old Parse , but nothing happening on Parse server side. Here is package.json:

> cat package.json 
> {
>   "name": "parse-server-example",
>   "version": "1.4.0",
>   "description": "An example Parse API server using the parse-server module",
>   "main": "index.js",
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/ParsePlatform/parse-server-example"
>   },
>   "license": "MIT",
>   "dependencies": {
>     "express": "~4.11.x",
>     "kerberos": "~0.0.x",
>     "parse": "~1.8.0",
>     "parse-server": "~2.2.12",
>     "deepcopy": "0.6.1",
>     "parse-server-push-adapter": "1.0.4"
>   },
>   "scripts": {
>     "start": "node index.js"
>   },
>   "engines": {
>     "node": ">=4.3"
>   }
> }

and curl request:

> curl -X POST \
>     -H "X-Parse-Application-Id: generic_string_from_original_parse" \
>     -H "X-Parse-Master-Key: generic_string_from_original_parse" \
>     -H "Content-Type: application/json" \
>     -d '{
>           "where": {
>             "deviceType": "android",
>         "objectId": "user_id"
>           },
>           "data": {
>             "title": "Test",
>             "alert": "Curl test over heroku."
>           }
>         }'\   https://notreal.herokuapp.com/parse/push

**Comment by brianyyz** [comment]
I had to create new APNS certificates (dev and prod) to get push notifications to work.
