### ISSUE TITLE
NPM start fails with custom parse-server dependency

### ISSUE THREAD

**Issue by acegreen** [parse-community/parse-server-example#237]
I tried to use parse-server master branch (it has an important fix) and the installation seems to have gone fine. I updated my index.js, etc and then tried npm install and it failed.

I add the dependency as such:
"parse-server": "ParsePlatform/parse-server#1fb7679"
and also 
"parse-server": "ParsePlatform/parse-server"

I also tried to what was suggested here but no luck
https://github.com/ParsePlatform/parse-server/issues/700

And tried to change the package BEFORE npm install, no luck

And I did rm -r node_modules and npm install several times, also no luck

./node_modules seems to contain parse-server but something isn't clicking. 

```
Error: Cannot find module 'parse-server'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/parse-server-2.2.15-withFix/index.js:5:19)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)

npm ERR! Linux 4.2.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-server-example@1.4.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls parse-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/parse-server-2.2.15-withFix/npm-debug.log
```

**Comment by acegreen** [comment]
@flovilmart maybe you can shed some light on this

**Comment by drew-gross** [comment]
Thats not the right syntax. Check the `npm` docs here for more info: https://docs.npmjs.com/files/package.json

**Comment by acegreen** [comment]
@drew-gross did you even try it? In the same docs you referenced, it says its a valid syntax and as mentioned it installs but won't run. I wouldn't close this issue until I tried it at least, so that it gives other a chance to look over it and potentially help, even if its a non-issue. Unless it skews your open/close ratio 

<img width="681" alt="screen shot 2016-07-10 at 6 03 15 am" src="https://cloud.githubusercontent.com/assets/10794609/16712910/13320e92-4664-11e6-851a-dff791617d84.png">

**Comment by acegreen** [comment]
To add to the above, I also tried:
"parse-server": "git://github.com/ParsePlatform/parse-server.git"

**Comment by acegreen** [comment]
@drew-gross can you actually try it or reopen the ticket so someone else can?

**Comment by acegreen** [comment]
More notes: if I reverse back to "2.2.15", it installs and starts as expected

**Comment by drew-gross** [comment]
Makes sense. I think this is more of an `npm` issue than a `parse-server` issue, but I'll leave this open in case someone wants to jump in.

**Comment by acegreen** [comment]
@drew-gross you haven't tried this out by any chance? I'm sure I'm not the first to try to npm from the repo.

**Comment by drew-gross** [comment]
No I use `npm link` to remain on master. I think it's meant more for when you are developing npm modules but maybe it might work for you as well. Keep in mind we have a build step, which might complicate things.

**Comment by acegreen** [comment]
I tried linking but it didn't work. I linked from inside the node_modules. When you link do you link to the module inside that folder or do you got submodule and link to that?

**Comment by drew-gross** [comment]
We transpile ES6 to ES5 so we can support Node 4. This is done by running `npm run build` in the `parse-server` folder. `npm link` should be run from the `parse-server` folder as well.

**Comment by acegreen** [comment]
So 

In node_modules npm link parser-server ./parser-server
In parse-server npm link .....?

**Comment by flovilmart** [comment]
The main issue with referencing the repository is that the lib folder is ignored from git and all other folders are ignored from npm, so without using npm link, you end up having an incomplete package.

**Comment by acegreen** [comment]
@flovilmart thanks forgiving your feedback here. I did npm link. Can you detail where we need to link? I went inside the node_module and did npm link parse-server ./parse-server.

**Comment by flovilmart** [comment]
You just need to call `npm link path/to/parse-server` from the root folder containing your package.json

**Comment by acegreen** [comment]
@flovilmart 

<img width="1484" alt="screen shot 2016-07-10 at 5 42 49 pm" src="https://cloud.githubusercontent.com/assets/10794609/16716278/c9c9e1d2-46c5-11e6-9752-5e94899c12c7.png">

**Comment by flovilmart** [comment]
You need to clone the repository or add it as a submodule, then link it. Don't put it into node_modules as it's likely that node will clean it up.

**Comment by acegreen** [comment]
@flovilmart ran the following in parse-server-2.2.15-withFix (root of the example)
git submodule add https://github.com/parseplatform/parse-server
npm link parse-server ./parse-server

<img width="1099" alt="screen shot 2016-07-10 at 6 25 28 pm" src="https://cloud.githubusercontent.com/assets/10794609/16716492/cc9689dc-46cb-11e6-88cb-8c61abaf2d60.png">

**Comment by flovilmart** [comment]
According to the doc: 

https://docs.npmjs.com/cli/link

the command would be:

`npm link ./parse-server`

**Comment by acegreen** [comment]
That didm't work either. Also in your other issue you had it differently. i'll have look into the docs

<img width="1152" alt="screen shot 2016-07-10 at 7 25 07 pm" src="https://cloud.githubusercontent.com/assets/10794609/16716766/195b85b2-46d4-11e6-92d2-7b78da0fc0ea.png">

**Comment by acegreen** [comment]
@flovilmart @drew-gross are we sure there is nothing in the parse-server thats preventing this?

**Comment by drew-gross** [comment]
I use `npm link` myself. Maybe we can just do a release.

**Comment by acegreen** [comment]
You link the parse-server specifically? And a release would be ideal. I spent the last 24h dealing with this bs.

**Comment by arckdash** [comment]
Hi everybody! How is going ? I just cloned the project and I having the same  problem! :S 
Could someone solve it ?

**Comment by arckdash** [comment]
HI guys, I think I figure out, and now It's working for me.

The solution was install the least version of NodeJs and npm, due the specification says:
**Make sure you have at least Node 4.3. node --version**
so... make sure that you have the latest nodeJs version

Here a tutorial about how do it into different linux's versions.
https://www.metachris.com/2015/10/how-to-install-nodejs-5-on-centos-and-ubuntu/

I think It's a silly thing, but if you are new, this can help you.

**Comment by kendrikat** [comment]
Using node v6.9.3 

```
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.4.0 start: `node index.js`
npm ERR! Exit status 1

```

**Comment by timwekken** [comment]
Anybody have any ideas on this?
The submodule/link solution works locally, but doesn't work on Heroku.

**Comment by fathurrohmane** [comment]
I solved this by 
1. Updating node js from 4.X to 6.X
2. And follow this steps
[link](https://github.com/ParsePlatform/parse-server-example/issues/9#issuecomment-177337014)

Not sure with the second step, so I skip it but it works
