### ISSUE TITLE
Cannot Connect Parse Server Heroku with Android Application

### ISSUE THREAD

**Issue by R00t6** [parse-community/parse-server-example#238]
I have successfully deployed Parse Server on Heroku using Deploy on Heroku Button. I have also configured the index.js configurations as below: 

index.js 

```
var api = new ParseServer({
  serverURL: "https://parseservertest12.herokuapp.com",
  databaseURI: databaseUri || 'mongodb://heroku_jhwmv6c9:khhmh38a4u95krh1gbajni59rs@ds021034.mlab.com:21034/heroku_jhwmv6c9',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || 'myMasterKey' //Add your master key here. Keep it secret!
});
```

These are my var configs on the heroku settings page.

APP_ID : myAppId
MASTER_KEY : myMasterKey
MONGODB_URI : mongodb://heroku_jhwmv6c9:khhmh38a4u95krh1gbajni59rs@ds021034.mlab.com:21034/heroku_jhwmv6c9
PARSE_MOUNT : /parse
SERVER_URL : https://parseservertest12.herokuapp.com

I have also configure this build into my Android Application Class.

```
Parse.initialize(new Parse.Configuration.Builder(getApplicationContext())
            .applicationId("myAppId")
            .clientKey("myMasterKey")
            .server("https://parseservertest12.herokuapp.com/parse")
    .build()
    );

      ParseObject gameScore = new ParseObject("GameScore");
      gameScore.put("score", 1337);
      gameScore.put("playerName", "Sean Plott");
      gameScore.put("cheatMode", false);
      gameScore.saveInBackground(new SaveCallback() {
          public void done(ParseException e) {
              if (e == null) {
                  Log.i("Parse", "Save Succeeded");
              } else {
                  Log.i("Parse", "Save Failed");
              }
          }
      });


      ParseUser.enableAutomaticUser();
    ParseACL defaultACL = new ParseACL();
    // Optionally enable public read access.
    // defaultACL.setPublicReadAccess(true);
    ParseACL.setDefaultACL(defaultACL, true);
  }
```

And also initialized in AndroidManifest.xml

```
 <application
        android:name=".StarterApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <meta-data
            android:name="com.parse.APPLICATION_ID"
            android:value="@string/parse_app_id" />
        <meta-data
            android:name="com.parse.CLIENT_KEY"
            android:value="@string/parse_client_key" />
```

These are the string values:

```
<string name="parse_app_id">myAppId</string>
    <string name="parse_client_key">myMasterKey</string>
```

My application is ready on Android past 7 days. I am very familiar using Parse Android SDK that's why I don't want to move away from parse. I am trying to connect my android app since 7 days but its not creating objects on mongo lab. I have tried every possible tutorial I found online for connecting the android application but nothing works. Kindly help me resolve this issue because my project has been pending since then only because of the parse server.

**Comment by khanaldeepak** [comment]
Facing same problem since last week if you find the solution please share with me.. Thank you

**Comment by R00t6** [comment]
Couldn't find a solution to this yet. If you do please share it here.

**Comment by nickgerig** [comment]
@R00t6 This is probably better off on Stackoverflow but.... 

You do need the trailing slash in:

 `server("https://parseservertest12.herokuapp.com/parse"`

so it should be: 

`server("https://parseservertest12.herokuapp.com/parse/"`

**Comment by R00t6** [comment]
@nickgerig it is still not working have you connected your android app with parse heroku?

**Comment by sagaratalatti** [comment]
Has anyone been able to fix with this problem? I have done the same but I am not able to save data on Parse Server. Is Parse Server stable to use or should we go for alternate cloud service?

**Comment by IndDev** [comment]
Experiencing the same problems. It just says Save Failed when I run the android studio file that uses parse server with Heroku and Mlab.

Relevant java file: 

'/*
 * Copyright (c) 2015-present, Parse, LLC.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
package com.parse.starter;

import android.app.Application;
import android.util.Log;

import com.parse.Parse;
import com.parse.ParseACL;
import com.parse.ParseException;
import com.parse.ParseObject;
import com.parse.ParseUser;
import com.parse.SaveCallback;


public class StarterApplication extends Application {

  @Override
  public void onCreate() {
    super.onCreate();

    // Enable Local Datastore.
    Parse.enableLocalDatastore(this);

    // Add your initialization code here
    Parse.initialize(new Parse.Configuration.Builder(getApplicationContext())
            .applicationId("instagram34340389378937783")
            .clientKey("aslkndksndwdondknkda")
            .server("http://instagram9899.herokuapp.com/parse/")
    .build()
    );

      ParseObject gameScore = new ParseObject("GameScore");
      gameScore.put("score", 2133);
      gameScore.put("playerName", "Jim Plott");
      gameScore.put("cheatMode", false);
      gameScore.saveInBackground(new SaveCallback() {
          public void done(ParseException e) {
              if (e == null) {
                  Log.i("Parse", "Save Succeeded");
              } else {
                  Log.i("Parse", "Save Failed");
              }
          }
      });


      ParseUser.enableAutomaticUser();
    ParseACL defaultACL = new ParseACL();
    // Optionally enable public read access.
    // defaultACL.setPublicReadAccess(true);
    ParseACL.setDefaultACL(defaultACL, true);
  }
}
'

Log file from Android Studio:

`09-28 19:45:04.200 16825-16825/com.parse.starter W/System: ClassLoader referenced unknown path: /data/app/com.parse.starter-2/lib/x86
09-28 19:45:04.512 16825-16940/com.parse.starter D/NetworkSecurityConfig: No Network Security Config specified, using platform default
09-28 19:45:04.637 16825-16825/com.parse.starter W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-28 19:45:04.763 16825-16825/com.parse.starter W/gralloc_ranchu: Gralloc pipe failed
                                                                   
                                                                   [ 09-28 19:45:04.764 16825:16825 D/         ]
                                                                   HostConnection::get() New Host Connection established 0x9f422300, tid 16825
                                                                   
                                                                   
                                                                   [ 09-28 19:45:04.813 16825:16949 D/         ]
                                                                   HostConnection::get() New Host Connection established 0x9f422780, tid 16949
09-28 19:45:04.861 16825-16949/com.parse.starter I/OpenGLRenderer: Initialized EGL, version 1.4
09-28 19:45:04.861 16825-16949/com.parse.starter D/OpenGLRenderer: Swap behavior 1
09-28 19:45:34.285 16825-16825/com.parse.starter I/Parse: Save Failed
`

**Comment by IndDev** [comment]
Stacktrace after save failed-

```
Parse.initialize(new Parse.Configuration.Builder(getApplicationContext())
  .applicationId("myAppId")
  .server("http://myServerUrl/parse/")   // '/' important after 'parse'
  .build());

ParseObject testObject = new ParseObject("TestObject");
testObject.put("foo", "bar");
testObject.saveInBackground();
```

**Comment by plaudev** [comment]
Facing same issue. I notice that my code runs perfectly on actual device (6P) but on emulator: 
1. cannot login or logout - it just hangs without even returning an error & no callback at all
2. same thing with signup
3. gets `com.parse.ParseRequest$ParseRequestException: i/o failure` on write
