### ISSUE TITLE
Email template on parse-server-example

### ISSUE THREAD

**Issue by kwstasna** [parse-community/parse-server-example#248]
Hello.
Where is the location for the email templates?

**Comment by bcomeau** [comment]
You must use an adapter that support email templates.

The following ones are examples:
- [parse-server-mailgun-adapter-template](https://www.npmjs.com/package/parse-server-mailgun-adapter-template)
- [parse-server-mandrill-adapter](https://www.npmjs.com/package/parse-server-mandrill-adapter)
- [parse-server-mailjet-adapter](https://www.npmjs.com/package/parse-server-mailjet-adapter)
