### ISSUE TITLE
Update from parse-server-example to the latest parse-server

### ISSUE THREAD

**Issue by auching** [parse-community/parse-server-example#250]
I have deployed my app using **parse-server-example**, is there any instructions/guidelines on how to update it to the latest **parse-server**? I tried to copy the files directly but unsuccessful and I find the two very different...
I'm using Heroku + mLab and deploy it with the Dropbox option.

**Comment by lifeisfunny** [comment]
Parse server example using npm ,It only sets the min request version of dependencies

**Comment by auching** [comment]
so are they meant to serve different purpose? should I stick with 'parse-server-example'?  or redo everything from scratch again using the 'parse-server'?  please guide me a proper direction... thanks a lot.

**Comment by caesss** [comment]
I would appreciate help with this as well. I'm running 2.2.9 using Heroku + mLab too and I'm not entirely sure how to keep my "fork" updated with the latest version. Maybe this is more of a rookie question, my apologies.

**Comment by richard4339** [comment]
Update the parse server version in package.json from 2.2.12 to 2.2.19. It's that easy.

If using Heroku, commit said change then push. The push will have NPM automatically install the new server version.
