### ISSUE TITLE
100 XMLHttpRequest failed: "Unable to connect to the Parse API"

### ISSUE THREAD

**Issue by auching** [parse-community/parse-server-example#253]
I'm using this parse-server-example (2.2.7) in my hosted Parse server (Heroku + mongoDB), I use google analytics to keep track errors and I constantly find this error (over 10%):
100 XMLHttpRequest failed: "Unable to connect to the Parse API"

It happens once the app starts a query (not cloud function).  I already added this in my index.js as I googled it:

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

but this error still happens, so frustrating....  any help would be greatly appreciated...

**Comment by kfwerf** [comment]
did you manage to get this resolved, im struggling with this right now...

**Comment by auching** [comment]
no.. it's so random, can't even reproduce..

**Comment by kalitas** [comment]
here as well. all is working good (still local server), even curl is returning the object however i still get this error when using through cloudcode

**Comment by johndoehelloworld** [comment]
@auching , @kalitas : Were you guys able to fix this?

**Comment by markmssd** [comment]
Having the same issue. It works perfectly on iOS, but no luck on Android. Any suggestions?
