### ISSUE TITLE
What is the use of app.json file?

### ISSUE THREAD

**Issue by techyrajeev** [parse-community/parse-server-example#255]
I see there is app.json file present with configuration values but not used any where?
Please let me know if I am missing any trivial points.

**Comment by sdrew** [comment]
The `app.json` file is used for the [Heroku Button](https://blog.heroku.com/heroku-button) found in the `README`, for one-click installation and setup on the [Heroku](https://www.heroku.com/) platform.

You don't actually have to worry about it unless you're using Heroku.
