### ISSUE TITLE
[SOLVED] Unable to ensure uniqueness for usernames/user email addresses (pls marks as closed)

### ISSUE THREAD

**Issue by mikall** [parse-community/parse-server-example#258]
## Stupid error typing password, sorry.

Hi all,
I installed parse server example on different vps providers (AWS with EC2 and EB or DigitalOcean)
and linked the AS with an mlab db with this connection string: 

> mongodb://USER:PWD@ds123456.mlab.com:61475/MYDB

as suggested in the mlab guide and it works, I can read and write on this DB.
My servers are running ParseServer v: 2.2.17

BUT, after `npm start` I see some warnings:

```
warn: Unable to ensure uniqueness for usernames:  MongoError: Authentication failed.
    at Function.MongoError.create (/root/parse-server-example/node_modules/mongodb-core/lib/error.js:31:11)
    at /root/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:439:41
    at authenticateStragglers (/root/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:399:16)
    at null.messageHandler (/root/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:421:5)
    at Socket.<anonymous> (/root/parse-server-example/node_modules/mongodb-core/lib/connection/connection.js:294:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
warn: Unable to ensure uniqueness for user email addresses:  MongoError: Authentication failed.
    at Function.MongoError.create (/root/parse-server-example/node_modules/mongodb-core/lib/error.js:31:11)
    at /root/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:439:41
    at authenticateStragglers (/root/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:399:16)
    at null.messageHandler (/root/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:421:5)
    at Socket.<anonymous> (/root/parse-server-example/node_modules/mongodb-core/lib/connection/connection.js:294:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
```

Can someone explain me the meaning of these warnings? Can I ignore them or should I take some actions?

Thank you,
Michele

**Comment by rjpalermo1** [comment]
I've got the same issue...can you shed some light as to what your solution was?

**Comment by mikall** [comment]
Hi,
in my case I ran into a connection string issue. The application server was not able to contact the db server due to error typing the "mongodb://..." string.

I hope this helps.
BR
Michele

**Comment by rjpalermo1** [comment]
Thanks...didn't help.  I'm using Docker/Mac and this is driving me nuts!

**Comment by navidos86** [comment]
i have this issue when installing it on my own laptop (Mac OS El Capitain). 
I uninstalled node, NPM and installed those again, installed parse-server-example once again and getting this error. 

It would be great if someone can help me out with this. 

`warn: Unable to ensure uniqueness for usernames:  MongoError: failed to connect to server [localhost:27017] on first connect
    at null.<anonymous> (/Users/navidmirzaie/parse-server/node_modules/mongodb-core/lib/topologies/server.js:311:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/navidmirzaie/parse-server/node_modules/mongodb-core/lib/connection/pool.js:254:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/navidmirzaie/parse-server/node_modules/mongodb-core/lib/connection/connection.js:158:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
warn: Unable to ensure uniqueness for user email addresses:  MongoError: failed to connect to server [localhost:27017] on first connect
    at null.<anonymous> (/Users/navidmirzaie/parse-server/node_modules/mongodb-core/lib/topologies/server.js:311:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/navidmirzaie/parse-server/node_modules/mongodb-core/lib/connection/pool.js:254:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/navidmirzaie/parse-server/node_modules/mongodb-core/lib/connection/connection.js:158:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
^C
`

**Comment by rjpalermo1** [comment]
I solved this problem by creating a user on mongo db.

Go to your mongo server and


>mongo
>use <db-name>
>db.createUser( { user: "<db user>", pwd: "<db-password>", roles: [
"readWrite", "dbAdmin" ] })


*****************

Here are the steps I took for a Docker/Kitematatic setup on my Mac so I can
setup multiple servers/dbs easily.  This is very specific to my needs but
you should be able to use it and tweak to your own.

1. Create a folder for your setup (eg., /parse)
2. Create subfolders in this folder for server, data and dashboard
    ~parse/server
    ~ parse/data/db
    ~ parse/data/configdb
    ~ parse/dash
3.  git clone the following from your /parse directory:
   ~ git clone https://github.com/ParsePlatform/parse-server.git server
   ~ git clone https://github.com/ParsePlatform/parse-dashboard.git dash
4.  Go into your /server folder and npm install (I'm using latest node 6.x)
5.  Go into your /dash folder and npm install also

SET UP DOCKER / MONGO

6.  Install docker beta for MAC.
7.  Once installed, open Kitematic and install a mongo server from the base
mongo image
8.  Once the server is running, you can do a little customization for you
parse environment in Kitematic
~ change name of server to something like parse-mongo-db
~ change the localhost port to something like 29876 or a port number that
will remain static if you reboot the instance.  This port number will be
used in your parse server config file.
~ add the following variables...

[image: Inline image 1]

[image: Inline image 2]

Attach the parse/data/configdb and parse/data/db folders you created
initially to the volumes in the docker container - this keeps a local copy
of data and config on your machine in case you need to delete the current
mongo container and launch another (you just point the volumes on the new
mongo server to this folder again)

[image: Inline image 3]

Once that is done, save pressed and mongo server restarted click on the
EXEC button on the top of the mongo server
[image: Inline image 4]
This will launch an interactive shell on the Docker/mongo server.  We need
to create the db and user you set up in the ENV variables above.

From prompt

>mongo
>use <db-name>
>db.createUser( { user: "<db user>", pwd: "<db-password>", roles: [
"readWrite", "dbAdmin" ] })

You should get a success user created message.

PARSE SERVER setup.

1.  GO into the parse/server folder and run sh ./bootstrap.sh
2.  Click Y - enter through everything - don't worry about setting up
config options.
3.  Once complete and npm install finishes, copy/save the config.json as
 config_bak.json or something.
4.  Delete the contents of config.json and replace with the following.  The
values between <> are your own values EXCEPT for the appID and master key.
Those need to be whatever was auto-generate in the ootstrap process and are
in your now called config_bak.json file.

{
  "appId": "<FROM YOUR CONFIG_BAK.JSON FILE>",
  "masterKey": "<FROM YOUR CONFIG_BAK.JSON FILE>",
  "appName": "<YOUR_APP_NAME (note, must be lowercase, no spaces or special
chars)>",
  "cloud": "./cloud/main",
  "databaseURI": "mongodb:/<YOUR_DB_USER>:<YOUR_DB_USER_PW>@localhost:<
YOUR_DB_PORT>/<YOUR_DB>",
  "port": <YOUR_PORT>,
  "mountPath": "/<YOUR_MOUNT_PATH>",
  "serverURL": "http://localhost:<YOUR_PORT>/<YOUR_MOUNT_PATH>",
  "publicServerURL": "http://localhost:<YOUR_PORT>",
  "verifyUserEmails": "<YOUR_CHOICE true or false>",
  "preventLoginWithUnverifiedEmail": "<YOUR_CHOICE true or false>",
  "emailAdapter" : {
    "module": "parse-server-simple-mailgun-adapter",
    "options": {
      "fromAddress": <YOUR_FROM>",
      "domain": "YOUR_MAILGUN_DOMAIN",
      "apiKey": "YOUR_MAILGUN_API_KEY",
      "verificationSubject": "Please verify your e-mail for %appname%",
      "verificationBody": "Hi,\n\nYou are being asked to confirm the e-mail
address %email% with %appname%\n\nClick here to confirm it:\n%link%",
      "passwordResetSubject": "Password Reset Request for %appname%",
      "passwordResetBody": "Hi,\n\nYou requested a password reset for
%appname%.\n\nClick here to reset it:\n%link%"
    }
  },

  "filesAdapter": {
  "module": "parse-server-fs-adapter",
  "options": {
    "filesSubDirectory": "/<YOUR_CHOICE>"
    }
  },

  "oauth": {
    "twitter": {
      "consumer_key": "",
      "consumer_secret": ""
    },
    "facebook": {
      "appIds": ""
    },
    "my_custom_auth": {
       "module": "",
       "option1": "",
       "option2": ""
     }
  },

  "allowClientClassCreation": "<YOUR_CHOICE true or false>",
  "enableAnonymousUsers": "<YOUR_CHOICE true or false>",
  "maxUploadSize": "<YOUR_CHOICE default 20mb or enter 5mb for example>",
  "revokeSessionOnPasswordReset": "<YOUR_CHOICE true or false>"
}

5.  npm start (and you should be live and ready to rock!)

.....In my setup, I have four servers talking to four different databases.
That means I have 4 Mongo Docker containers, each with different port
numbers tied to four parse-servers in folders...

~ parse/server/demo MOUNT_PATH=/demo PORT=/2441
~ parse/server/stage MOUNT_PATH=/stage PORT=/2442
~ parse/server/live1 MOUNT_PATH=/app PORT=/2443
~ parse/server/live2 MOUNT_PATH=/app PORT=/2444

I haven't tried yet but am pretty sure you can have all 4 servers point to
the same database just by keeping the  "databaseURI" in the config.json the
same in all 4 servers

DASHBOARD

1.  Go into your parse/dash folder
2.  Create a parse-dashboard-config.json and use the following config file
replacing with your values.  The following will show a single user config
with the 4 apps referenced above

{
  "apps": [

    {
      "serverURL": "http://localhost:2441/demo",
      "appId": "<APP_ID>",
      "masterKey": "<MASTER_KEY>",
      "appName": "<APP_NAME>",
      "iconName": "<ICON_NAME.png or .jpg>",
      "production": false
    },

    {
      "serverURL": "http://localhost:2442/stage",
      "appId": "<APP_ID>",
      "masterKey": "<MASTER_KEY>",
      "appName": "<APP_NAME>",
      "iconName": "<ICON_NAME.png or .jpg>",
      "production": false
    },

    {
      "serverURL": "http://localhost:2443/app",
      "appId": "<APP_ID>",
      "masterKey": "<MASTER_KEY>",
      "appName": "<APP_NAME>",
      "iconName": "<ICON_NAME.png or .jpg>",
      "production": true
    },

    {
      "serverURL": "http://localhost:2444/app",
      "appId": "<APP_ID>",
      "masterKey": "<MASTER_KEY>",
      "appName": "<APP_NAME>",
      "iconName": "<ICON_NAME.png or .jpg>",
      "production": true
    }
  ],

  "users": [
    {
      "user":"<MY_PERSONAL_USERNAME>",
      "pass":"<MY_PERSOANL_PASSWORD>",
      "apps": [
        {"appId": "<APP_ID for :2441/demo>"},
        {"appId": "APP_ID for :2442/demo>>"},
        {"appId": "<APP_ID for :2443/app>"},
        {"appId": "APP_ID for :2444/spp>>"}
      ]
    }
  ],

  "iconsFolder": "<YOUR parse/dash/<foldername> - for example "icons"  >"
}

3.  Finally, go into the parse/dash/package.json and in under the "scripts"
block change the "start" key to the following (replace --port with your
desired port number or leave out to default to port 4040):

~     "start": "parse-dashboard --port 4444 --config
parse-dashboard-config.json"

That should be all.   Hope it helps.

**Comment by navidos86** [comment]
@rjpalermo1 tnx for your detail instructions. And if i don't want to install a docker station? can i take the same steps?

Tnx.

**Comment by rjpalermo1** [comment]
Sure - your localhost will be 27017 - make sure mongo is running and set
your db / db user.

The mongo thing is super easy to set up and manage and you won't run into
problems or port conflicts like you might with a single mongo instance
running o your local machine...you should try it.

**Comment by navidos86** [comment]
@rjpalermo1 is their any possibility to provide me the screenshots you posted with your first post? tmakes things easier for me. I want to run it on a dock machine also. 

Tnx.

**Comment by rjpalermo1** [comment]
![img4](https://cloud.githubusercontent.com/assets/7153565/18329691/c5d24cf0-7522-11e6-8a46-5a737f37fc8c.png)
![img3](https://cloud.githubusercontent.com/assets/7153565/18329694/c711dd9c-7522-11e6-8f06-b182a31ed5f2.png)
![img1](https://cloud.githubusercontent.com/assets/7153565/18329699/ccb83836-7522-11e6-9932-8d508928be9f.png)

![img2](https://cloud.githubusercontent.com/assets/7153565/18329698/c9664182-7522-11e6-8b47-7cc7f883938f.png)

**Comment by navidos86** [comment]
@rjpalermo1 now im getting the following error when i do : npm start or even npm start config.json

```
Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! fonk@ start: `parse-server ./config.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fonk@ start script 'parse-server ./config.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fonk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     parse-server ./config.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fonk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fonk
npm ERR! There is likely additional logging output above.

```

What can i do to fix this problem?

**Comment by rjpalermo1** [comment]
What is `fonk@ start: `parse-server ./config.json`` ?????

The start script you are using is invalid in your package.json

Here is a sample package.json to use

{ "name": "demo-server", "scripts": { "start": "parse-server ./config.json"
}, "dependencies": { "parse-server": "^2.0.0" } }

**Comment by navidos86** [comment]
Aaaah its in package.json great!! Tnx soo much hopefully it will work this time.

**Comment by dennyjohnk** [comment]
@rjpalermo1 how can go to mongo shell to create user if mongoDb  throws error ?

**Comment by rjpalermo1** [comment]
@dennyjohnk I can't recall much of this issue - I actually moved away from Docker and set up my own VPS (12 servers now) with mongo replica sets and Parse running round robin on 2 stand-alone servers.  I may get back to Docker again soon as I open this up to devs...

Regarding your question - I thing the problem I was having was Parse Server -> Mongo initialization.  Mongo itself was fine and I could use the common mongo shell without involving Parse server
