### ISSUE TITLE
eb create on AWS elastic beanstalk gives an error 

### ISSUE THREAD

**Issue by aliasad106** [parse-community/parse-server-example#262]
I have downloaded the latest version of Parse-server-example 
I am trying to deploy parse server on AWS elastic beanstalk with Docker and ebcli.

When I run the command 
`eb create --envvars DATABASE_URI=mongodb://USERNAME:PASSWORD@ds051851.mlab.com:51851/MYDB,APP_ID=MYAPPID,MASTER_KEY=MYMASTERKEY` 

I get this error 

```
ERROR: "option_settings" in one of the configuration files failed validation. More details to follow.
ERROR: Unknown or duplicate parameter: NodeCommand 
ERROR: Failed to launch environment.
```

referred to issues #60 and https://github.com/yongjhih/docker-parse-server/issues/21 both didn't help

**Comment by aliasad106** [comment]
I have copied the contents of the extracted "parse-server-example" to another folder. Which means it didn't copy .ebextensions with it. Now when i ran `eb create` it worked.

**Comment by ryanrca** [comment]
I have suddenly run into this on my production environment.  I have run the same command, on the same EB environment with the same .cfg.yml file for months without issue.

Then one day, I run "eb deploy" and I get this exact error.  

```
INFO: Environment update is starting.                               
ERROR: "option_settings" in one of the configuration files failed validation. More details to follow.
ERROR: Unknown or duplicate parameter: NodeCommand                  
ERROR: Failed to deploy application.                                
                                                                      
ERROR: Failed to deploy application.

```

**Comment by ryanrca** [comment]
I am reproducing this with both eb create and eb deploy.
Anybody else?
