### ISSUE TITLE
[Error]: Failed to run command eventually with error

### ISSUE THREAD

**Issue by kashif789us** [parse-community/parse-server-example#266]
Hello guys. I am running parse server on AWS. Today I have run into a weird issue. This is the first time I am seeing this and I do not why.

I am getting the following error continuously:

>  [Error]: Failed to run command eventually with error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

Please guide me whats the problem and how to fix it. Thank you

**Comment by pejalo** [comment]
I am getting this error from running findObjectsInBackgroundWithBlock: on a PFQuery object. The same exact query seems to fail roughly half the time with this error.
