### ISSUE TITLE
Could not save PFFile to Parse Server

### ISSUE THREAD

**Issue by samhon18** [parse-community/parse-server-example#267]
I have followed the instruction of parser-server-sample to setup a Parse server in Heroku and backed by mongodb in mLab. All configuration variables (MONGODB_URI, APP_ID, MASTER_KEY, SERVER_URL) are setup properly. An object can be saved into mongdb successfully through Parse server. 

But when i tried to test file upload function using the commands below

```
curl -X POST \
  -H "X-Parse-Application-Id: <my_app_id>" \
  -H "Content-Type: text/plain" \
  -d 'Hello, World!' \
  http://<my-heroku-app-url>/parse/files/hello.txt 
```

I got the response below

`{"code":130,"error":"Could not store file."}`

From Heroku log, I can see http status code is 400 for that request

```
2016-09-04T18:14:03.579933+00:00 heroku[router]: at=info method=POST path="/parse/files/hello.txt" host=<my-app-host> request_id=4942fc3c-20ee-40c5-9dc9-721bd8817c87 fwd="<my-ip>" dyno=web.1 connect=0ms service=21ms status=400 bytes=535
```

Noted that I use the default `GridStoreAdapter`. From the document, there should be nothing to setup. 

I also tried to setup publicServerURL but the file upload function failed too.

```
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  publicServerURL: process.env.SERVER_URL || 'http://localhost:1337/parse', // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});

```

**Comment by clarkee1066** [comment]
I have had some success with setting publicServerURL in index.js in the same way as you, but now I have two identical environments on AWS ElasticBeanstalk where one consistently works with file uploads and one doesn't.  Note that they have both worked at some point so this seems to be a transient problem.

I get same `{"code":130,"error":"Could not store file."}` error when POSTing a file.   

nginx log shows error 400 :

`172.31.20.75 - - [05/Sep/2016:13:31:00 +0000] "POST /parse/files/img%20-%201.jpg HTTP/1.1" 400 44 "{referer}" "{user agent}" "{my ip}"`

**Comment by clarkee1066** [comment]
An update that may help anyone else with same `{"code":130,"error":"Could not store file."}`  when sending a file to Parse server.

My setup is parse server hosted on AWS ElasticBeanstalk with data stored on mLab.   When using mLab shared (single-node) MongoDB database everything is fine.  When using resilient replica-set paid-for MongoDB on mLab I consistently get code 130 "could not store file" when Parse server attempts to save to mLab. 

I've got around this issue by using the S3 Files Adapter instead of default gridstore adapter - follow instructions about half way down here [http://docs.mlab.com/migrating-from-parse/](url)

**Comment by HackShitUp** [comment]
I'm actually having the same issue currently with files being saved to AWS S3...
