### ISSUE TITLE
How can I manage multiple Parse Server instances?

### ISSUE THREAD

**Issue by brennanMKE** [parse-community/parse-server-example#270]
I have multiple Parse apps. The instructions to install Parse Server explain that it is necessary to fork the main repository but GitHub only allows for forking a repository once. I'd like to read instruction son managing multiple instances of Parse Server. I have 2 main use cases.
1. Distinct Parse Server instances for separate apps
2. Instances for Staging and Production

I expect that I can simply copy the files from the repository into unique repositories and connect the upstream to pull updates for Parse Server occasionally. That would make the first use case manageable. For the 2nd use case I'd like to use environment variables to distinguish between Staging and Production while working locally and when deploying to Heroku.

Is there any documentation covering these use cases? If not, I'd like to start writing up these docs to include with the Parse Server and Heroku docs.

**Comment by maravilhosinga** [comment]
You will have to install Parse-server-exemple in diferents forders like this

Parse server 1 and Parse server 2

Go to user forder and git server one like this:

`https://github.com/ParsePlatform/parse-server-example.git Parse-Server1`

Then to create an other parse server just repeat the same things but set name to Parse-Server2

`https://github.com/ParsePlatform/parse-server-example.git Parse-Server2`

Then to install all dependecies you will need to go in each directory and install there. like this

`$ cd /home/parse/Parse-Server1
$ npm install`

Then just hit

$ cd

And go to forder 2 like this

`$ cd /home/parse/Parse-Server2
$ npm install`

Then to run your servers you will need to go in each forder and tape

`$ npm start`

If you want to run in production or in backgroud install "pm2" globally and just run

in your server forder like this 

`$ cd /home/parse/Parse-Server2
$ pm2 start index.js`
or 
`$ cd /home/Parse-Server2
$ pm2 start Parse-Server2`

Your server will keed running even when you quit or reboot a system.

If you've made changes in your files go in your root or main user and just type:

`$ pm2 restart all`

a2hosting.com is offering VPS from 5$
Hope this helps

**Comment by brennanMKE** [comment]
Thanks @maravilhosinga, I adapted your instructions to Heroku since that is what I am using.

After I installed Parse Server using the install button and used the Heroku CLI to clone the app locally I was left with an empty repository. I did not know what to do. Below are the steps I needed to get files into that folder so that I can start editing these files and pushing them to my own Git repository and also push the update to Heroku.

I've also created a [Gist](https://gist.github.com/brennanMKE/ae38ec0fecb8dfee117373dbbd9ee5a0) with these instructions.

## Parse Server Installation on Heroku

1. Create an account on [Heroku](http://www.heroku.com/)
2. Verify the Heroku account by adding a credit card (It will not be charged anything on the free tier.)
3. Open the [Parse Server](https://github.com/ParsePlatform/parse-server-example) page in your web browser 
4. Click the Install on Heroku buttton
5. Follow the instructions to create a new Heroku app

At this point the app is deployed and running on Heroku with a MongDB instance. Next you will want a local copy of the files from the Parse Server repository that you can manage in your own repository. You will push changes to your own origin and also deploy to Heroku using Git through the Heroku CLI to a Heroku remote.

1. Install the [Heroku CLI](https://devcenter.heroku.com/articles/heroku-command-line)
2. Create an empty repository on GitHub for the new app
3. Use the commands below to get a local copy of Parse Server

The commands below use the Heroku CLI and Git to access the app hosted on Heroku as well as put files into the empty repository created in the step above.

```sh
heroku git:clone -a MYAPP
cd MYAPP/
git remote add origin https://github.com/ParsePlatform/parse-server-example.git
git pull origin master
git remote set-url origin git@github.com:USERNAME/MYAPP.git
git push
git push heroku master
```

With the files pushed to your own GitHub repository and the app deployed to Heroku you will now want to be able to pull changes from the upstream occasionally to stay up to date. The commands below will add an upstream, fetch updates and merge to master.

```sh
git remote add upstream https://github.com/ParsePlatform/parse-server-example.git
git fetch upstream -v
git merge upstream/master
```
