### ISSUE TITLE
"Error: 100 XMLHttpRequest failed: \"Unable to connect to the Parse API\"

### ISSUE THREAD

**Issue by kfwerf** [parse-community/parse-server-example#279]
Hi,

I can't for the life of me seem to get connection to the parse API on heroku, this might be something obvious but at the moment i cannot get any connection to it.

`http://d4d-server.herokuapp.com/parse/functions/hello`

for instance works,

i setup the server as:

```
var protocol = process.env.HTTPS ? 'https://' : 'http://';
var port = process.env.PORT || 1337;

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

var api = new ParseServer({
  databaseURI: databaseUri || 'xxx' || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'xxx',
  masterKey: process.env.MASTER_KEY || 'xxx', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || protocol + 'localhost:' + port + '/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});
```

NOTE: i marked my app id, database and master key with xxx

However it still seems like it cannot connect via Heroku. When i run it locally it runs via, either via npm start or via heroku local i can get it to work, i think this is some sort of https issue but i cant get any feedback from the app what is failing.

Is this a true issue or can someone direct me in what im suppose to do here?

**Comment by johndoehelloworld** [comment]
@kfwerf Were you able to fix this?
