### ISSUE TITLE
Is new parse-server support "push_time" ?

### ISSUE THREAD

**Issue by zhangxiao918** [parse-community/parse-server-example#281]
Hi,guys:
   i want to know is new parse-server support "push_time" for client send ?

**Comment by ericgopak** [comment]
Nope, seems that Parse Server does not support `push_time`. However, one lovely Tiffany has proposed a workaround for server-side scripting: https://medium.com/@tiffany.ricks/parse-server-scheduled-push-notifications-hack-2ae873995b5b#.bgiyb1461
