### ISSUE TITLE
unable to update parse server to the new version 

### ISSUE THREAD

**Issue by tanzeelrana** [parse-community/parse-server-example#285]
how can I update the parse server ? I tried 

Update to latest version from source

cd parse-server
git checkout master
git pull
cd ..
git commit -am 'Updates parse-server to latest version'

can someone update this repo to have the latest parse server version ?
The newer version of parse server on the parse website has some new functionality that this version of the server is missing such as jobs.

Thanks in advance :)

**Comment by maravilhosinga** [comment]
You can update Parse server using npm, it's the best way.

cd parse-server
npm update
