### ISSUE TITLE
npm doesn't start !

### ISSUE THREAD

**Issue by v1gnus** [parse-community/parse-server-example#291]
down is my npm-debug.log file

info it worked if it ends with ok
verbose cli [ 'node', '/usr/bin/npm', 'start' ]
info using npm@1.1.4
info using node@v0.6.12
verbose config file /home/vagrant/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
verbose caching /home/vagrant/server/parse-server-example/package.json
verbose loadDefaults parse-server-example@1.4.0
verbose run-script [ 'prestart', 'start', 'poststart' ]
info prestart parse-server-example@1.4.0
info start parse-server-example@1.4.0
verbose unsafe-perm in lifecycle true
silly exec sh "-c" "node index.js"
silly spawning [ 'sh',
silly spawning   [ '-c', 'node index.js' ],
silly spawning   '/home/vagrant/server/parse-server-example' ]
info parse-server-example@1.4.0 Failed to exec start script
ERR! parse-server-example@1.4.0 start: `node index.js`
ERR! `sh "-c" "node index.js"` failed with 1
ERR! 
ERR! Failed at the parse-server-example@1.4.0 start script.
ERR! This is most likely a problem with the parse-server-example package,
ERR! not with npm itself.
ERR! Tell the author that this fails on your system:
ERR!     node index.js
ERR! You can get their info via:
ERR!     npm owner ls parse-server-example
ERR! There is likely additional logging output above.
ERR! 
ERR! System Linux 3.2.0-23-generic
ERR! command "node" "/usr/bin/npm" "start"
ERR! cwd /home/vagrant/server/parse-server-example
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! code ELIFECYCLE
ERR! message parse-server-example@1.4.0 start: `node index.js`
ERR! message `sh "-c" "node index.js"` failed with 1
ERR! errno {}
verbose exit [ 1, true ]

**Comment by dlipiz** [comment]
Hey im having the same issue. Im just wondering if you were able to fix it

**Comment by v1gnus** [comment]
Yeah, for my case i had to run the git bash as administrator, when log in my vagrantBox. Hope it helps
