### ISSUE TITLE
Overriding Successfully verified your email! Template in Parse Sever Example

### ISSUE THREAD

**Issue by gateway** [parse-community/parse-server-example#292]
Is their a way to create your own override of the paser-server html template verify_email_success.html that can be customized in the parse server example area?

FYI im not talking about the emails that get sent out, but after you click the link.  Thoughts?

**Comment by andreas-cindra** [comment]
For Invalid Link, Password Reset Success, and Verify Email Success page, you can go to your Parse Folder > node_modules > parse-server > public_html , there are 3 html files.
For the reset password view you can go to  Parse > node_modules > parse-server > views > choose_password, if you open it on text editor it has html file structure, I don't know the reason actually why the file extension isn't .html.

Hope it's helpful.

**Comment by lenart** [comment]
I'm still getting to know my way around nodejs and parse-server but the answer @andreas-cindra provided is very invasive (you'll have to change them each time you update `parse-server`). Instead there are variables exposed that can be customized when initializing parse server. Inside `./node_modules/parse-server/lib/Config.js` I've found `customPages` variable where you can set things like `invalidLinkURL`, `passwordResetSuccess` and more.
