### ISSUE TITLE
Error 403 in JS sdk

### ISSUE THREAD

**Issue by anehico** [parse-community/parse-server-example#298]
Hi, I am Andrés from Colombia and i have a problem with my app in Parse Server.

i have my own Parse Server in AWS (EC2 Exactly) with the parse-server from bitnami, my own BD is in mlab, if i open the url directly from parse server, i can to see the "parse-dashboard" with the dates and the files correctly (the files is in S3 of AWS). But i try to connect with javascript, in the client to appears the "Error 403" and i don't know how to solve. =(

i try with javascript code, and without javascript code (as it is in the documentation)

i really to need help please.

(I am Sorry from my english)

**Comment by mlm249** [comment]
Experiencing same issue here.

Had an older version of this project working and wanted to update, but now I'm getting back {"error":"unauthorized"} for my test requests to my local server

**Comment by fmendoza** [comment]
same here. Any solution?

**Comment by brianyyz** [comment]
Hard to say what's going on unless you provide some config, code and responses. Simple question are you setting the right keys ?

**Comment by mlm249** [comment]
My setup ended up working with 2.2.23

**Comment by fmendoza** [comment]
I'm receiving this error:

`Error handling request: ParseError { code: 209, message: 'invalid session token' } code=209, message=invalid session token`

**Comment by maxMint** [comment]
If anyone needs immediate solution see:
https://gist.github.com/maxMint/70b079de2a7047aea1e4c68c19b72ff9

slightly changed sdk code to send proper headers.
