### ISSUE TITLE
error in uploading apis to AWS Beanstalk

### ISSUE THREAD

**Issue by morewin** [parse-community/parse-server-example#303]
Hi I am uploading parse-server-example.zip to my AWS Beanstalk.

I have attached my zip file.

They said;

"Environment health has transitioned from Severe to Degraded. 100.0 % of the requests are failing with HTTP 5xx. Impaired services on all instances." and I failed every time.

[parse-example.zip](https://github.com/ParsePlatform/parse-server-example/files/602522/parse-example.zip)

Please let me know if I can get this fixed.

Thank you.

**Comment by harolhiguera** [comment]
Hi Morewin!!, Did you fix it?
