### ISSUE TITLE
Why 'account setting' not show in my parse-dashboard ?

### ISSUE THREAD

**Issue by a1am1n** [parse-community/parse-server-example#307]
![screenshot from 2016-11-28 15 35 25](https://cloud.githubusercontent.com/assets/20919542/20663052/4fd7fdb2-b580-11e6-9c0d-ee661f19956b.png)
![screenshot from 2016-11-28 15 35 19](https://cloud.githubusercontent.com/assets/20919542/20663053/4fda8596-b580-11e6-8883-cdd30e1b9824.png)
see plz my parse-dashboard...why it is happened?
what i have to do ? 
why its show Server not reachable: unable to connect to server
Why 'account setting' not show in my parse-dashboard ?

**Comment by kwstasna** [comment]
try putting this address on your browser and comment here what it prints

`138.197.0.255:1337/parse`

**Comment by maxto024** [comment]
check your parse first if it  ok 

then check your parse-dashboard configuration  specially in the app  url
