### ISSUE TITLE
Delete value thru dashboard and api console

### ISSUE THREAD

**Issue by juliusneria** [parse-community/parse-server-example#310]
![capture](https://cloud.githubusercontent.com/assets/8121088/20989651/6edf705e-bd10-11e6-9412-f313b14af323.PNG)
I cant delete my data from my dashboard.. also in api console. everytime i try to delete this thing shows up

error: Error handling request: ParseError {
  code: 107,
  message: 'cannot route DELETE \\classes\\Shift\\Rtyl9b8wQK' } code=107, message=cannot route DELETE \classes\Shift\Rtyl9b8wQK

here is my server log

**Comment by tylyo** [comment]
same problem to me
did somebody solve it?
