### ISSUE TITLE
File Size

### ISSUE THREAD

**Issue by pupoo** [parse-community/parse-server-example#317]
Have created parse server on EC2.  Can download and upload files to a maximum of 20mb.  how can i increase the file size limit?  i can not locate the filesrouter.js through the SSH connection.  at a loss as to what to do here

**Comment by tsanthosh** [comment]
Are you saving your PFFiles in AWS S3 Buckets? If yes, have you configured your server to manage this using `filesadapter`?

**Comment by pupoo** [comment]
Yes i have configured the filesadapter.  and set the maxUploadSize in my index.js file  now i can upload files to about 40mb then anything larger won't upload.
