### ISSUE TITLE
Android Project doesn't contain index.js file?

### ISSUE THREAD

**Issue by grantespo** [parse-community/parse-server-example#318]
I'm trying to implement push notifications in my android app. 

I did some research and saw that I had to configure stuff in index.js. But because I deployed to Heroku, my project doesn't contain an index.js file.

All I was able to to was to get an "Installation" class on my parse-server. But this installation doesn't send as a notification.

**Comment by taylorknopp** [comment]
This may help you.
stackoverflow.com/questions/42255907/where-can-i-access-my-index-js-file-if-i-deployed-to-heroku-parse-from-the-websi
