### ISSUE TITLE
server auto close process issue

### ISSUE THREAD

**Issue by AnChiChang** [parse-community/parse-server-example#329]
Dear all

I had run parse server example on my personal environment(environment detail list below).
And I have run server use the command "node index.js &" make sure server is on in server background. Server is smooth and normal, and can see process by "ps -ef"

However, for a while I have not access server(like over one night). I had checked process, node index process is normal. But, when I execute some cloud code via my app like below, server process will disappear in background, can't see the process by ps -ef. I don't know why and parse server log without any error log. Have any expert can help to guild me to clarify the problem cause by Ubuntu, Node, or Parse server?

my current environment:
OS Ubuntu Release 16.04
Parse server version 2.2.25 beta-1
Node version V6.0.0

Cloud code like below:
Parse.Cloud.define("createNewUser", function(request, response) {
    
    var username = request.params.username;
    var pwd = request.params.pwd;
    var email = request.params.email;
    
    var name = request.params.name;
    var active = request.params.active;
    var companyobjectid = request.params.companyobjectid;
    var kgobjectid = request.params.kgobjectid;
    var lianobjectid = request.params.lianobjectid;
    
    var user = new Parse.User();
    user.set("username", username);
    user.set("password", pwd);
    user.set("email", email);

    // other fields can be set just like with Parse.Object
    user.set("name", name);
    
    var company = Parse.Object.extend("FI_Company");
    var companypointer = new company();
    companypointer.id = companyobjectid;
    user.set("pcompany", companypointer);

    user.set("active", active);
    
    user.signUp(null, {
      success: function(user) {
          response.success(user);
      },
      error: function(user, error) {
          response.error("error");
      }
    });

    
});

**Comment by presscorp** [comment]
I have almost the same problem. During the server start every request works as expected. It starts crashing about after 24 hours. But in my case server crashes, when I send user log in request with wrong username or password, or trying to sign up with unverified email.

**Comment by Miladinho** [comment]
Guys, do me a favor and check out your parse-server folder under node_modules, if there is a folder called bin but not src, then it means that parse-server-example has an issue and is using a way older version of parse-server for some reason. I suggest taking a look at the code in the parse-server github repo and comparing it to the parse-server that parse-server-example contains in node_modules. You will see what I am talking about.

**Comment by AnChiChang** [comment]
Hi @Miladinho 

After check, I had saw the bin folder that you mention under node_modules/parse-server/bin, it's content three files dev, parse-live-query-server, and parse-server.
Then what can I do? update new parse-server?
Thanks for helping.

**Comment by Miladinho** [comment]
@AnChiChang 

Ok I made a mistake, i meant "lib" folder not "bin". The parse-server-example version of parse-server comes with a lib folder where all the server code i contained, the newest version has an "src" folder, and the syntax of the code is different (more modern?). Your best bet is to not use the example and run parse-server raw.

**Comment by AnChiChang** [comment]
@Miladinho thanks for your reply.

I had used npm update parse-server, therefore, currently parse-server version 2.3.6. So, after update parse-server, the problem will be solve?
I use parse-server-example because I want use Express with Parse-Server, have any suggest?

**Comment by Miladinho** [comment]
@AnChiChang The information I was giving you is wrong, there is no issue with the code. I have noticed though that you are using a really old version of parse-server, that may be the issues, I believe the latest is 2.3.6, try using that one.

**Comment by presscorp** [comment]
I tried to setup my own parse-server v2.3.6 (not parse-server-example). It started normally. After all I still face the same issue. It handled all requests perfectly at the beginning. Then after about 6-8 (maybe less, didn't test for less) hours I checked, it still crushes when I try to log in with wrong user/password. Is it possible that the way I launch parse-server is incorrect. This is what I usually do
`npm start &`. Is it proper way to start?

**Comment by presscorp** [comment]
I managed to make parse-server work flawlessly with help of systemd. I launched it 17 hours ago (without Restart option), and is still on track. I think my problem was that I used to start parse-server as a regular process in background with this command `npm start &`.
