### ISSUE TITLE
Aws deploy, noob question

### ISSUE THREAD

**Issue by pcegarra** [parse-community/parse-server-example#331]
I have my url http://sample-env.xxxx.us-west-2.elasticbeanstalk.com/ running but how can I get some response from parse server?

 http://sample-env.xxxx.us-west-2.elasticbeanstalk.com/parse is not working, any idea? Thanks

**Comment by maxto024** [comment]
i think the default port must be 1337 if you didnt change it  so this is how you can access 

http://sample-env.xxxx.us-west-2.elasticbeanstalk.com:1337

only use /parse when you want to request  any thing but if you just want to check if it is live or not you can check without /parse  

https://parseplatform.github.io/docs/rest/guide/

check here for more rest api 

thnks

**Comment by pcegarra** [comment]
Thanks for the answer, Im getting no response with the port :1337, then my next noob question is, what is the best practice to connect the instance with a mongo db?  Now Im using mlab, but my server is in Frankfurt and my DB in Ireland..

**Comment by pcegarra** [comment]
This my DATABASE_URI:

mongodb://myUsername:myPassword@ds13370.mlab.com:15110/pcegarra

Is it ok?

**Comment by maxto024** [comment]
yes i think  thats ok  this is how i did it 
var api = new ParseServer({
 databaseURI: databaseUri || 'mongodb://username:pass@34.249.29.201:27017/parse',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || '',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});

**Comment by pcegarra** [comment]
Ok I will try, Are you using a vpc for the mongo db or are you using mlab too?

**Comment by maxto024** [comment]
no for mongodb i  install in aws ec2   configure it as production then use it 
also parse I install another aws ec2
