### ISSUE TITLE
Is IOS Push Working on example server?

### ISSUE THREAD

**Issue by taylorknopp** [parse-community/parse-server-example#337]
On our server, we have Android push working flawlessly, but we have been fighting for months now to get IOS push working.  We can't send push notifications from the dashboard or via cloud code. I have configured the server with our development .p12 cert from apple and the appropriate bundle ID and passphrase.  I got no errors from parse at any point in the process of sending push notifications. Does anyone else have this problem or a solution or anything?

**Comment by NAVNEETSINGH1** [comment]
even i m facing the same issue

**Comment by brianyyz** [comment]
I've got push working on IOS using the example as my starting point. Can you post your configuration details and any log output ?  It is hard to help out without them.

**Comment by NAVNEETSINGH1** [comment]
// Example express application adding the parse-server module to expose Parse
// compatible API routes.

var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');

var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  
  push: {
		
		ios: {
			pfx: 'certs/DrawTogether_APNS_Dev.p12', // the path and filename to the .p12 file you exported earlier. 
			cert: '', //certs/DrawTogether_APNS_Dev.pem   If not using the .p12 format, the path to the certificate PEM to load from disk
			bundleId: 'com.drawtogether', // The bundle identifier associated with your app
			key: '', //asdf1234 If not using the .p12 format, the path to the private key PEM to load from disk
			production: false // Specifies which environment to connect to: Production (if true) or 
		}
	},
  masterKey: process.env.MASTER_KEY || 'myMasterKey', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!');
});

// There will be a test page available on the /test path of your server url
// Remove this before launching your app
app.get('/test', function(req, res) {
  res.sendFile(path.join(__dirname, '/public/test.html'));
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});
var pushQuery = new Parse.Query(Parse.Installation);
Parse.Push.send({

        channels: [ "Giants" ],
        data: {
            alert: "The Giants Mets 2-3."
        }
    }, { useMasterKey: true });
// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(httpServer);

**Comment by NAVNEETSINGH1** [comment]
and my log error is 

at=info method=POST path="/parse/push" host=parseexampleapp.herokuapp.com request_id=ae2eb73d-6eb8-4310-8200-239cc5c9fef5 fwd="219.91.156.54" dyno=web.1 connect=1ms service=21ms status=403 bytes=537 protocol=https
2017-05-14T20:17:21.509624+00:00 app[web.1]: [31merror[39m: Error generating response. { Error: unauthorized: master key is required
2017-05-14T20:17:21.509628+00:00 app[web.1]:     at promiseEnforceMasterKeyAccess (/app/node_modules/parse-server/lib/middlewares.js:299:17)
2017-05-14T20:17:21.509629+00:00 app[web.1]:     at /app/node_modules/parse-server/lib/PromiseRouter.js:132:22
2017-05-14T20:17:21.509631+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:135:7) status: 403, message: 'unauthorized: master key is required' } status=403, message=unauthorized: master key is required
2017-05-14T20:17:21.519389+00:00 app[web.1]: Error: unauthorized: master key is required
2017-05-14T20:17:21.519393+00:00 app[web.1]:     at promiseEnforceMasterKeyAccess (/app/node_modules/parse-server/lib/middlewares.js:299:17)
2017-05-14T20:17:21.519393+00:00 app[web.1]:     at /app/node_modules/parse-server/lib/PromiseRouter.js:132:22
2017-05-14T20:17:21.519394+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by NAVNEETSINGH1** [comment]
sample push notification  request looks like  this altough some keys are secret so cannot copy as it is  


curl -H "Host: parseexampleapp.herokuapp.com"     -H "X-Parse-Client-Version: i1.14.2.x.y.z" -H "Accept: */*" -H "X-Parse-Session-Token: r:b217783dc0f7aaf9c2dd8eaeb4aa3106" -H "X-Parse-Application-Id: myappIs" -H "X-Parse-Client-Key: y clientkey" -H "X-Parse-Installation-Id: e058a0fc-babb-442f-8feb-xyz" -H "X-Parse-OS-Version: 10.3.1 (14E304)" -H "Accept-Language: en-us" -H "Content-Type: application/json; charset=utf-8" -H "User-Agent: drawtogether/1 CFNetwork/811.4.18 Darwin/16.5.0" -H "X-Parse-App-Build-Version: 1" -H "X-Parse-App-Display-Version: 1.7" --data-binary "{\"where\":{\"user\":{\"$inQuery\":{\"where\":{\"objectId\":\"Ur4WqyyxS5\"},\"className\":\"_User\"}}},\"data\":{\"id\":\"JRhyPtSBUP\",\"sounds\":\"UILocalNotificationDefaultSoundName\",\"alert\":{\"loc-key\":\"It's your turn!\"},\"badge\":\"Increment\"}}" --compressed 
https://parseexampleapp.herokuapp.com/parse/push

**Comment by NAVNEETSINGH1** [comment]
please help to me to run push notification of parse -server example code  on heroku with given index.js  Thanks in advance 

well if u can tell me from where in code i can enable push for clientid request also instead of getting master key 
thankyou so much in advance:)

**Comment by brianyyz** [comment]
If the error occurs on your curl example then I'd say you are trying to access an object without the required permissions so you'd need to send the master key in the headers. If it is occurring in your cloud code function make sure you've specified {"useMasterKey": true} on the Parse operation.

**Comment by NAVNEETSINGH1** [comment]
how to set in cloud code  {"useMasterKey": true}  my cloud.js is  this much only 


Parse.Cloud.define('hello', function(req, res) {
  res.success('Hi');
});

**Comment by NAVNEETSINGH1** [comment]
also from ios app i cant set master key i can do it using client key only

**Comment by brianyyz** [comment]
First off, enabling client push is almost never a good idea. It opens your app up to abuse by malicious users or hacking.

Instead your app should call a cloud function in which you can validate the requesting user, do any processing you need to do and then use Parse functions to send the push. That way you never expose the master key to the client and you can protect from spoofed requests or hacked clients.

Caveat - I hacked the two examples below together very quickly so there may be errors in them. I'll clean them up if I get time later.

For example, in your app you could 
```javascript
        PFCloud.callFunction(inBackground: someCloudfunction, withParameters: [parameter1 : value1 , parameter2 : value2], block: { (response: Any?, error: Error?) in            
            if error == nil && response != nil {
                // the cloud function completed successfully
            } else {
                if error != nil {
                    // handle the error that was returned
                } else {
                    // server returned a null response
                }
            }
        })
```

The cloud code function - likely in your main.js - could be

```javascript
Parse.Cloud.define("someCloudFunction", function(request, response) {

    var query = new Parse.Query(constants.someClassName);
    query.equalTo(constants.objectIdName, request.params.value1);
    
    query.first({ useMasterKey: true }).then(function(anObjectWeAreInterestedIn) {
        // guard against empty result set
        if (anObjectWeAreInterestedIn) {
       var installationQuery = new Parse.Query(Parse.Installation);
       installationQuery.equalTo(constants.userFieldName, someObjectWeAreInterestedIn.user);
        Parse.Push.send({
            where: installationQuery,
            data: {
                alert: messageToSend,
                badge: 1,
                "key": "7"
            }
        }, { useMasterKey: true }).then(function() {
            console.log("push sent");
            response.success();
        }, function(error) {
            console.log("push send error " + error);
            response.error(" Error: error sending push notifications " + error);
        });
    },
    function(error) {
        console.log("Error: " + error);
        response.error(" Error: Unable to find ");
    });
});

```
