### ISSUE TITLE
"Unauthorized" error with push notifications / cloud code

### ISSUE THREAD

**Issue by bmueller** [parse-community/parse-server-example#346]
I haven't touched my Parse server in almost a year, but today I had to upload new push notification certificates to keep everything running. I added the new p12 certificates (without changing anything else), pushed the changes to Heroku, and immediately started getting an "[Error]: unauthorized (Code: 0, Version: 1.13.0)" message in my console. In my Heroku logs, I was getting code 403 for every push I tried to send using Cloud code. I could still access my dashboard and view data, etc. So it seems like my Cloud code is just broken in some way.

I noticed that my Parse Server version jumped from 2.2.16 to 2.2.25 after pushing these changes. When I reverted the changes and went back to 2.2.16, everything started working again.

Is there a way to require a specific version of Parse Server so I can just keep using 2.2.16 and get these new certificates uploaded? Or, failing that, is there some way to push the certificates to Heroku without updating the Parse Server to a new version?

**Comment by brianyyz** [comment]
If you're using parse-server-example the package.json specifies a "*" for parse-server so that it always picks up the most recent version. You can lock it to a specific version if you need to - which is what I did to avoid a broken push delivery count.

**Comment by bmueller** [comment]
Just tried that and it looks like it's working now. It was previously set to "~2.2.16", which I guess means something different than just "2.2.16" - but removing the tilde kept the server at the correct version number.
