### ISSUE TITLE
Failed to connect to <my_app_name>.herokuapp.com port 1337: Connection refused

### ISSUE THREAD

**Issue by codesdk** [parse-community/parse-server-example#347]
Deployed this successfully on heroku at <my_app_name>.herokuapp.com 

However, when I run (from my localhost) 

==> curl -X GET -H "X-Parse-Application-Id: <my_server>" -H "Content-Type: application/json" -d '{}' https://<my_app_name>.herokuapp.com:1337/parse/classes/WallPost

I get the following error
curl: (7) Failed to connect to <my_app_name>.herokuapp.com port 1337: Connection refused

I even tried to set PORT env variable as follows 

==> heroku config:set PORT=1337
Setting PORT and restarting ⬢ <my_app_name>... done, v6
PORT: 1337

But it returns the same error.

**Comment by jincod** [comment]
@codesdk 
You should use serverUrl without port: `https://<my_app_name>.herokuapp.com/parse/classes/WallPost`
