### ISSUE TITLE
Full End to End Tutorial

### ISSUE THREAD

**Issue by bstillitano** [parse-community/parse-server-example#369]
I’ve written a complete end to end tutorial in setting up parse for public usage. 

Posting here as possible help for any other mobile devs or non backend devs. 

https://medium.com/@b.stillitano95/setting-up-a-public-parse-instance-in-2020-with-parse-server-and-parse-dashboard-555e9b5ac16a?sk=42e9483d07f89b60163a57958995afed

**Comment by mtrezza** [comment]
@bstillitano Thanks for writing this tutorial, I think it can be helpful to some users.

I think we could add a link list of 3rd party tutorials / E2E guides to the Parse Server repo to give this tutorial more visibility and also to consolidate such tutorials for other Parse Server developers.

@TomWFox What do you think? We already have the [Running Parse Server elsewhere](https://github.com/parse-community/parse-server#running-parse-server-elsewhere) list. Should we add an "External tutorials" list?

**Comment by mtrezza** [comment]
@bstillitano Would you be fine with it if we add your tutorial link to our [Community links](https://github.com/parse-community/parse-server/wiki#tutorials-on-how-to-deploy-your-own-parse-server)?

**Comment by bstillitano** [comment]
Hi,

That would be fine with me.

**Comment by TomWFox** [comment]
Sounds good @mtrezza

**Comment by mtrezza** [comment]
I am closing this as the link as been added to the [Community links](https://github.com/parse-community/parse-server/wiki#tutorials-on-how-to-deploy-your-own-parse-server). Thanks again for creating this helpful tutorial and making the life of new Parse developers easier.
