### ISSUE TITLE
Stopped working after updating parse-server version from 2.2.1 to * 

### ISSUE THREAD

**Issue by mrharsh2804** [parse-community/parse-server-example#382]
I have deployed latest parse-server-example copy on Heroku. I needed to update the minimum version of parse-server to 2.8.4 to get ready to migrate to MongoDB Atlas from mLab.
The application works fine with 2.8.4 but if I put *, it stops working. I tried different versions and noticed that it works until 3.4.4 and then from 3.5.0 onwards it stops working.
I am not sure how exactly to find out what's wrong or whats the error. Please advise.
Please let me know if there are any changes required.

**Comment by davimacedo** [comment]
Have you checked this guide?
https://github.com/parse-community/parse-server/blob/master/3.0.0.md

**Comment by mrharsh2804** [comment]
I have a fresh copy of this repo. I just change the variable names and it worked previously with 2.2.1. In fact it worked until 3.4.4. 
Do I still have to make these changes to the code?

**Comment by mtrezza** [comment]
I'm closing this as it lacks essential information. Feel free to edit your question using the issue template and we can re-open this issue.
