### ISSUE TITLE
Add GitHub Actions to Parse Server Example

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server-example#383]
I think it would be helpful to:

- Define masterKey / appId via `dotenv`
- Add `.env` file but have in .gitignore
- Have a GitHub Actions workflow that runs `npm run lint` on cloud code, just like the master repo
- Have a spec folder that starts a Parse Server off index.js with a temporary database
- Have an example spec to show developers how to ensure their cloud code is running as expected

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [1.2.0](https://github.com/parse-community/parse-server-example/releases/tag/1.2.0)
