### ISSUE TITLE
Invalid mongoURI using MongoLab

### ISSUE THREAD

**Issue by thewizster** [parse-community/parse-server-example#40]
I have a db setup with MongoLab and am using the mongoDB URI provided by MongoLab but I am getting the following error when I test using the example hello function:

`Uncaught internal server error. [Error: Invalid mongoURI: <myMongoURI>  at ExportAdapter.connect (D:\home\site\wwwroot\node_modules\parse-server\ExportAdapter.js:39:11)`

Running on Azure.

---

Update: I switched to a non-cluster MongoLab URI (Sandbox) this error has gone away.

Are MongoLab clusters supported?

**Comment by adamontherun** [comment]
+1

**Comment by themichael123** [comment]
This error is caused by this commit: https://github.com/ParsePlatform/parse-server/pull/148

If you switch to an earlier version it should work.

**Comment by themichael123** [comment]
confirmed parse-server@2.0.4 is working with replica sets.

**Comment by thewizster** [comment]
Confirm it works in parse-server@2.0.4 for me now.

parse-server@2.0.7 it is broken
