### ISSUE TITLE
Can't run NPM install

### ISSUE THREAD

**Issue by farasjibran** [parse-community/parse-server-example#411]
i cant run npm install in this repo after clone, it show error like this. can you please help this things?

> npm ERR! code 1
> npm ERR! path C:\Users\faras\Documents\Kerjaan Kantor\parse-server-example\node_modules\kerberos
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@8.4.1
> npm ERR! gyp info using node@16.13.1 | win32 | x64
> npm ERR! gyp info find Python using Python version 3.10.2 found at "C:\Users\faras\AppData\Local\Programs\Python\Python310\python.exe"
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
> npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
> npm ERR! gyp ERR! find VS looking for Visual Studio 2015
> npm ERR! gyp ERR! find VS - not found
> npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
> npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
> npm ERR! gyp ERR! find VS For more information consult the documentation at:
> npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
> npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\faras\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
> npm ERR! gyp ERR! stack     at C:\Users\faras\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
> npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\faras\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
> npm ERR! gyp ERR! stack     at C:\Users\faras\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
> npm ERR! gyp ERR! stack     at C:\Users\faras\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
> npm ERR! gyp ERR! stack     at C:\Users\faras\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
> npm ERR! gyp ERR! stack     at C:\Users\faras\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
> npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
> npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
> npm ERR! gyp ERR! System Windows_NT 10.0.22000
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\faras\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd C:\Users\faras\Documents\Kerjaan Kantor\parse-server-example\node_modules\kerberos
> npm ERR! gyp ERR! node -v v16.13.1
> npm ERR! gyp ERR! node-gyp -v v8.4.1
> npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\faras\AppData\Local\npm-cache\_logs\2022-02-02T12_24_31_214Z-debug-0.log

**Comment by a60231023** [comment]
i am getting the same error 
if you have solved this can you please help

**Comment by farasjibran** [comment]
> i am getting the same error if you have solved this can you please help

i am just installed visual studio in my windows, and then i select the development tools in there

**Comment by physxP** [comment]
changed node to 11.0 using node version manager and it is working now

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved. See the Parse Server compatibility table that corresponds to the Parse Server version used in this example repo.
