### ISSUE TITLE
Upgrade Parse Server example to use latest Parse Server 5.x

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server-example#417]
Just a small upgrade needed:

- Upgrade to use Parse Server 5.x
- Change `engines` in `package.json` use use the same as the version to which Parse Server is upgraded

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [1.2.0](https://github.com/parse-community/parse-server-example/releases/tag/1.2.0)
