### ISSUE TITLE
ParseFile: can't save image. parse server Azure

### ISSUE THREAD

**Issue by arrivaldwis** [parse-community/parse-server-example#73]
I'm using the latest Parse SDK, .NET, MongoLab and Azure from parse-server-example repo. when I'm try to uploading image it's shown error:

```
Unhandled exception has occurred in your application. 
If you click Continue, the application will ignore this error and attempt to continue. 
If you click Quit, the application will close immediately.

Invalid file upload.
```

i see same questions in parse-server repo, and it's will fixed in parse-server 2.1.3. when it update, i try to redeploy this example repo in azure, but it's still can't upload a file/image.

**Comment by estylehq** [comment]
Use parse-azure-storage-adapter.

Create blob storage on azure.

Add to package.json this line in dependencies : "parse-server-azure-storage": "0.3.0".

and set configuration adapter below this : https://github.com/felixrieseberg/parse-server-azure-storage.

very easy.
