### ISSUE TITLE
Android Push Notification

### ISSUE THREAD

**Issue by thamer898** [parse-community/parse-server-example#85]
Can any one help me to integrate my app with GCM to support push notification ?

**Comment by zeluspudding** [comment]
Follow [these general instructions](https://github.com/ParsePlatform/parse-server/wiki/Push#quick-start). When you get to the step where you need to create a GCM push notification key follow [these specific steps](https://documentation.onesignal.com/v2.0/docs/android-generating-a-gcm-push-notification-key) (do no more, do no less). Know that your `senderId` is your *Project number*.
