### ISSUE TITLE
Non root routes break Push Notifications

### ISSUE THREAD

**Issue by shaneseaton** [parse-community/parse-server-example#87]
After modifying the example slightly to add push configs, and testing with CURL at /parse/push everything was working perfectly. Then I added cloud code to do some pushes and it wouldn't work. (Parse.Push.send)

Looks like the Parse.Push api is set to a default REST end point of "push" which isn't being routed to /parse/push

My work around for now is to set the PARSE_MOUNT to "/" which isn't a great solution, but works if you need it. 

I haven't tested, but after looking at (https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/Push.js) I suspect something like this in the index.js or perhaps cloud/main.js file might work.

```
var MyPushController = {
  send(data: PushData, options: RequestOptions) {
    var RESTController = CoreManager.getRESTController();

    var request = RESTController.request(
      'POST',
      '/parse/push', //here is my change
      data,
      { useMasterKey: !!options.useMasterKey }
    );

    return request._thenRunCallbacks(options);
  }
}

CoreManager.setPushController(MyPushController);
```

Clearly neither are great solutions, but I think ParseServer, or the ParseJSAPI might need looking at?

**Comment by rschweda** [comment]
Ran into the same problem. My solution was replacing:
```
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);
```
with  
`app.use('/parse', api);`

I also changed the serverURL property of api to:
`serverURL: 'https://my-app-name.herokuapp.com/parse',`
in` index.js`.

**Comment by yz** [comment]
Having the exact same issue with push notification using the /parse mount.
